file:
  profileImagePath: classpath:/

spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_member?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: eunii
    password: 775312

  sql:
    init:
      mode: always

  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 100MB

  # spring data jpa 설정
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true


jwt:
  header: Authorization
  secret: c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK
  token-validity-in-seconds: 86400

logging:
  level:
    com.leesh: debug